## Indexing

In [1]:
import numpy as np

In [ ]:
# positive indexing
arr1 = np.array([12,4,2,4])
print(f"The value at index 0 is : {arr1[0]}")
print(f"The value at index 1 is : {arr1[1]}")
print(f"The value at index 3 is : {arr1[2]}")
print(f"The value at index 4 is : {arr1[3]}")

The value at index 0 is : 12
The value at index 0 is : 4
The value at index 0 is : 2
The value at index 0 is : 4


In [ ]:
# negative indexing
arr2 = np.array([3,4,3,34])
print(f"The value at index 3 : {arr2[-1]}")
print(f"The value at index 2 : {arr2[-2]}")
print(f"The value at index 1 : {arr2[-3]}")
print(f"The value at index 0 : {arr2[-4]}")

The value at index 0 : 34
The value at index 1 : 3
The value at index 2 : 4
The value at index 3 : 3


## Slicing

In [ ]:
# positive index slicing
arr3 = np.array([23,5,3,5,4])
print(arr3[1:4])
print(arr3[:5:2])
print(arr3[:])

[5 3 5]
[23  3  4]
[23  5  3  5  4]


In [ ]:
# negative index slicing
arr4 = np.array([23,5,6,7,78,3])
print(f"The array is : {arr4}")
print(arr4[-5:-2])
print(arr4[:-3])

The array is : [23  5  6  7 78  3]
[5 6 7]
[23  5  6]


In [14]:
# array index slicing
arr5 = np.array([23,67,34,76,67,32])
print(arr5[[2 , 4]])
print(arr5[[3 , 5]])

[34 67]
[76 32]


In [16]:
# Boolean indexing
arr6 = np.array([23,76,4,56,45])
print(arr6[[False , False , True , True , True]])
print(arr6[[True , False , False , True , False]])

[ 4 56 45]
[23 56]


In [ ]:
# Slicing the array using condition 
arr7 = np.array([23,67,34,89,45,890])
print(arr7[arr7 > 50])
print(arr7[arr7 > 850])

[ 67  89 890]
[890]


In [8]:
arr8 = np.array([[54,34,56,54] , [23,6,43,54] , [45,23,34,4]])
print(arr8.shape)

(3, 4)
